"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = RootLayout;
exports.metadata = void 0;
var _react = _interopRequireDefault(require("react"));
var _nextjs = require("@clerk/nextjs");
var _google = require("next/font/google");
require("./globals.css");
var __jsx = _react["default"].createElement;
var geistSans = (0, _google.Geist)({
  variable: '--font-geist-sans',
  subsets: ['latin']
});
var geistMono = (0, _google.Geist_Mono)({
  variable: '--font-geist-mono',
  subsets: ['latin']
});
var metadata = exports.metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app'
};
function RootLayout(_ref) {
  var children = _ref.children;
  return __jsx(_nextjs.ClerkProvider, null, __jsx("html", {
    lang: "en"
  }, __jsx("body", {
    className: "".concat(geistSans.variable, " ").concat(geistMono.variable, " antialiased")
  }, __jsx("header", {
    className: "flex justify-end items-center p-4 gap-4 h-16"
  }, __jsx(_nextjs.SignedOut, null, __jsx(_nextjs.SignInButton, null), __jsx(_nextjs.SignUpButton, null, __jsx("button", {
    className: "bg-sky-600 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer"
  }, "Sign Up"))), __jsx(_nextjs.SignedIn, null, __jsx(_nextjs.UserButton, null))), children)));
}